language: node_js
node_js:
  - "10"
services:
  - docker
before_install:
  - docker-compose up --no-start moviedbTest
  - docker-compose start moviedbTest
  - sleep 5
  - docker ps
  - docker-compose logs
script: npm run test
