version: "3"
services:
  testmoviedb:
    image: mongo:4.0.8
    ports:
      - "27017:27017"
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=testmdb
      - MONGO_INITDB_ROOT_PASSWORD=testchangeme
      - MONGO_INITDB_DATABASE=testmoviedb
